In [9]:
import torch
import numpy as np
x = torch.FloatTensor([9,3]).view([-1, 1])
y = torch.FloatTensor([7,500]).view([-1, 1])
sigma = torch.FloatTensor([1,200]).view([-1, 1])
d = torch.distributions.normal.Normal(0, sigma)
print -d.log_prob(y-x)
print -torch.log(1 - d.cdf(y-x))

d = torch.distributions.gumbel.Gumbel(0, sigma)
z = (x-y)/sigma
cdf = torch.exp(-torch.exp(-z))
print cdf
print d.cdf(x-y)

tensor([[2.9189],
        [9.3049]])
tensor([[0.0230],
        [5.0394]])
tensor([[8.7342e-01],
        [6.1373e-06]])
tensor([[8.7342e-01],
        [6.1393e-06]])


In [ ]:

# # x = torch.FloatTensor([0.5084]).view([-1, 1])
# # sigma = torch.FloatTensor([5]).view([-1, 1])
# # y = torch.FloatTensor([1607]).view([-1, 1])
# x = torch.FloatTensor([0]).view([-1, 1])
# sigma = torch.FloatTensor([5]).view([-1, 1])
# y = torch.FloatTensor([200]).view([-1, 1])
# u = 


# d = torch.distributions.normal.Normal(0, 3)
# loss = -d.log_prob(x)    
# z = (x-y) / sigma
# print loss, -torch.log(1 - d.cdf(x))
# pdf = z+torch.exp(-z) + torch.log(sigma)
# cdf = torch.exp()
# print pdf
# print torch.exp(-z)
# print 

# d = torch.distributions.normal.Normal(y, sigma)
# loss = -d.log_prob(x)    
# print loss
# z = torch.pow(x-y, 2) / (2*torch.pow(sigma, 2))
# pdf = torch.exp(-z) / (sigma*np.sqrt(2*np.pi))
# print torch.exp(-z)
# print -torch.log(pdf)
# print z + torch.log(sigma*np.sqrt(2*np.pi))